name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Dry run (no actual release)'
        required: false
        type: boolean
        default: false

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci --legacy-peer-deps

      - uses: nrwl/nx-set-shas@v4

      # Configure git for commits
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      # Set up dummy Firebase config for CI builds
      - name: Set up Firebase config for CI
        run: cp apps/demo/angular/src/firebase/firebase-config.dummy.ts apps/demo/angular/src/firebase/firebase-config.ts

      # Run tests and build before release
      - name: Run tests and build
        run: npx nx affected -t lint test build

      # Build the plugin for release
      - name: Build plugin for release
        run: nx build firemono-nx

      # Check if there are any changes that warrant a release
      - name: Check for releasable changes
        id: changes
        run: |
          if npx nx release changelog --dry-run | grep -q "No changes"; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      # Automatic release based on conventional commits
      - name: Release
        if: steps.changes.outputs.skip == 'false' && github.event_name == 'push' && !inputs.dry-run
        run: npx nx release --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Dry run (manual trigger or to see what would be released)
      - name: Release Dry Run
        if: inputs.dry-run || (github.event_name == 'workflow_dispatch' && !inputs.dry-run)
        run: npx nx release --dry-run